// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx8mLg3RXLCgeVYL_wz6RjhnhI5wBRTeE',
    appId: '1:435864417888:web:ebda9d6b5d590bbbcab505',
    messagingSenderId: '435864417888',
    projectId: 'fir-1test-68896',
    authDomain: 'fir-1test-68896.firebaseapp.com',
    storageBucket: 'fir-1test-68896.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXsI_mMTbCzJgQ5LBv_lQD6e_Oev3lMsQ',
    appId: '1:435864417888:android:1da9f02e6c700fb6cab505',
    messagingSenderId: '435864417888',
    projectId: 'fir-1test-68896',
    storageBucket: 'fir-1test-68896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdjNgoCp5rJNJZeLk_6l0Ykxf30kdgeNU',
    appId: '1:435864417888:ios:ae6a22baa6ad63bacab505',
    messagingSenderId: '435864417888',
    projectId: 'fir-1test-68896',
    storageBucket: 'fir-1test-68896.appspot.com',
    iosClientId: '435864417888-7hk08o1jifh1p69uv2g9g1rv7ma85e4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdjNgoCp5rJNJZeLk_6l0Ykxf30kdgeNU',
    appId: '1:435864417888:ios:ae6a22baa6ad63bacab505',
    messagingSenderId: '435864417888',
    projectId: 'fir-1test-68896',
    storageBucket: 'fir-1test-68896.appspot.com',
    iosClientId: '435864417888-7hk08o1jifh1p69uv2g9g1rv7ma85e4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseapp',
  );
}
